/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEditorRouteImport } from './routes/admin.editor'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as AdminPedidoIdRouteImport } from './routes/admin.pedido.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorRoute = AdminEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidoIdRoute = AdminPedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pedido/$id': typeof AdminPedidoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pedido/$id': typeof AdminPedidoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pedido/$id': typeof AdminPedidoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/checkout'
    | '/conta'
    | '/admin/dashboard'
    | '/admin/editor'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/pedido/$id'
    | '/produto/$id'
    | '/admin/'
    | '/admin/pedido/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/checkout'
    | '/conta'
    | '/admin/dashboard'
    | '/admin/editor'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/pedido/$id'
    | '/produto/$id'
    | '/admin'
    | '/admin/pedido/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/checkout'
    | '/conta'
    | '/admin/dashboard'
    | '/admin/editor'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/pedido/$id'
    | '/produto/$id'
    | '/admin/'
    | '/admin/pedido/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editor': {
      id: '/admin/editor'
      path: '/editor'
      fullPath: '/admin/editor'
      preLoaderRoute: typeof AdminEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedido/$id': {
      id: '/admin/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/admin/pedido/$id'
      preLoaderRoute: typeof AdminPedidoIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEditorRoute: typeof AdminEditorRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPedidoIdRoute: typeof AdminPedidoIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEditorRoute: AdminEditorRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPedidoIdRoute: AdminPedidoIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
